web_app/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register('locations', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))
]

"""
CRUD
C -> Create: POST
R -> Read: GET
U -> Update: PUT
D -> Delete: DESTROY
"""

web_app/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/sterge/', views.delete_location, name='sterge'),
    path('<int:pk>/dezactiveaza', views.deactivate_location, name='dezactiveaza'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
]

web_app/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'companies'

urlpatterns = [
    path('', views.CompanyView.as_view(), name='list_companies'),
    path('add/', views.CreateCompanyView.as_view(), name='add'),
    path('<int:pk>/update/', views.UpdateCompanyView.as_view(), name='modify'),
    path('<int:pk>/delete/', views.delete_company, name='delete'),
    path('<int:pk>/deactivate/', views.deactivate_company, name='deactivate'),
    path('<int:pk>/activate/', views.activate_company, name='activate'),
]

web_app/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('locations/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('profile/', include('user_profile.urls')),
    path('api/', include('api.urls')),
]

web_app/user_profile/urls.py
from django.urls import path
from user_profile import views

app_name = 'userprofile'

urlpatterns = [
    path('start_timesheet/', views.new_timesheet, name='start_pontaj'),
    path('end_timesheet/', views.stop_timesheet, name='stop_pontaj'),
]

web_app/aplicatie1/models.py
from django.db import models


# Create your models here.
class Location(models.Model):

    city = models.CharField(max_length=100)
    country = models.CharField(max_length=90)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.country} -> {self.city}"


class AuditLocation(models.Model):
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=90)
    active = models.BooleanField(default=1)
    location = models.IntegerField()
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.country} -> {self.city}"

web_app/aplicatie2/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    location = models.ForeignKey("aplicatie1.Location", on_delete=models.CASCADE)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.name}"

web_app/user_profile/models.py
from django.db import models


class Logs(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    action = models.CharField(max_length=10)
    url = models.CharField(max_length=100)


class Pontaj(models.Model):

    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True)

web_app/api/views.py
from rest_framework import viewsets

from api.serializers import LocationSerializers
from aplicatie1.models import Location


# Create your views here.
class LocationViewSet(viewsets.ModelViewSet):
    queryset = Location.objects.all().order_by('city')
    serializer_class = LocationSerializers

web_app/aplicatie1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView
from aplicatie1.models import Location, AuditLocation


# Create your views here.
class LocationView(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'aplicatie1/locations_index.html'
    paginate_by = 5
    queryset = model.objects.all().order_by('id')

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data()
        data['page'] = self.request.GET.get('page') if self.request.GET.get('page') else 1
        return data



class CreateLocationView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Location
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'
    permission_required = 'user_profile.add_pontaj'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Location
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


@login_required
def delete_location(request, pk):
    location_value = Location.objects.get(id=pk)
    AuditLocation.objects.create(location=location_value.id,
                                 city=location_value.city,
                                 country=location_value.country,
                                 active=location_value.active,
                                 user_id=request.user.id)
    Location.objects.filter(id=pk).delete()
    return redirect(f'/locations/?page={request.GET.get("page")}')


@login_required
def deactivate_location(request, pk):
    Location.objects.filter(id=pk).update(active=0)
    return redirect(f'/locations/?page={request.GET.get("page")}')


@login_required
def activate_location(request, pk):
    Location.objects.filter(id=pk).update(active=1)
    return redirect(f'/locations/?page={request.GET.get("page")}')

web_app/aplicatie2/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView
from aplicatie2.models import Company


class CompanyView(LoginRequiredMixin, ListView):
    model = Company
    template_name = 'aplicatie2/companies_index.html'
    paginate_by = 5
    queryset = model.objects.all().order_by('id')

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data()
        data['page'] = self.request.GET.get('page') if self.request.GET.get('page') else 1
        return data


class CreateCompanyView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Company
    fields = ['name', 'website', 'location']
    template_name = 'aplicatie2/companies_form.html'
    # TODO: look into permissions
    permission_required = 'user_profile.add_pontaj'

    def get_success_url(self):
        return reverse('companies:list_companies')


class UpdateCompanyView(LoginRequiredMixin, UpdateView):
    model = Company
    fields = ['name', 'website', 'location']
    template_name = 'aplicatie2/companies_form.html'

    def get_success_url(self):
        return reverse('companies:list_companies')


@login_required
def delete_company(request, pk):
    Company.objects.filter(id=pk).delete()
    return redirect(f'/companies/?page={request.GET.get("page")}')


@login_required
def deactivate_company(request, pk):
    Company.objects.filter(id=pk).update(active=0)
    return redirect(f'/companies/?page={request.GET.get("page")}')


@login_required
def activate_company(request, pk):
    Company.objects.filter(id=pk).update(active=1)
    return redirect(f'/companies/?page={request.GET.get("page")}')

web_app/user_profile/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
import datetime
from user_profile.models import Pontaj


@login_required
def new_timesheet(request):
    Pontaj.objects.create(user_id=request.user.id,
                          start_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def stop_timesheet(request):
    Pontaj.objects.filter(user_id=request.user.id,
                          end_date=None).update(end_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

web_app/templates/aplicatie1/locations_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
    {% for field in form %}
        {{ field.label }} {{ field }} {{ field.errors }}
    {% endfor %}
    <button type="submit" class="btn btn-success">Salveaza</button>
    </form>
{% endblock %}

web_app/templates/aplicatie1/locations_index.html
{% extends 'base.html' %}
{% block content %}
    {% if perms.user_profile.add_pontaj %}
        <a class="btn btn-primary" href="{% url 'locations:adauga' %}">Adaugare locatii</a>
    {% endif %}
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>City</th>
            <th>Country</th>
            <th>State</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in location_list %}
            <tr>
                <td class="align-middle">{{ forloop.counter }}</td>
                <td class="align-middle">{{ item.city }}</td>
                <td class="align-middle">{{ item.country }}</td>
                <td class="align-middle">{% if item.active is True %}
                    Active
                {% else %}
                    Inactive
                {% endif %}</td>
                <td><a class="btn btn-success" href="{% url 'locations:modifica' item.id %}">Edit</a>
                    <a class="btn btn-danger" href="{% url 'locations:sterge' item.id %}?page={{ page }}">Delete</a>
                    {% if item.active is True %}
                        <a class="btn btn-info" href="{% url 'locations:dezactiveaza' item.id %}?page={{ page }}">Deactivate</a>
                    {% else %}
                        <a class="btn btn-success" href="{% url 'locations:activeaza' item.id %}?page={{ page }}">Activate</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex align-items-center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
                    {% else %}
                        <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
                {% else %}
                    <li class="disabled btn"><span>>></span></li>
                {% endif %}
                <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of {{ page_obj.paginator.count }}</span>
            </ul>
        {% endif %}
    </div>
{% endblock %}

web_app/templates/aplicatie2/companies_form.html
{% extends 'base.html' %}

{% block title %}
    Add company
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }} {{ field.errors }}
        {% endfor %}
        <button type="submit" class="btn btn-success">Save</button>
    </form>
{% endblock %}

web_app/templates/aplicatie2/companies_index.html
{% extends 'base.html' %}

{% block title %}
    Companies
{% endblock %}

{% block content %}
    {% if perms.user_profile.add_pontaj %}
        <a class="btn btn-primary mb-3" href="{% url 'companies:add' %}">Add companies</a>
    {% endif %}
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>Name</th>
            <th>Website</th>
            <th>Location</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in company_list %}
            <tr>
                <td class="align-middle">{{ forloop.counter }}</td>
                <td class="align-middle">{{ item.name }}</td>
                <td class="align-middle">{{ item.website }}</td>
                <td class="align-middle">{{ item.location.country }}, {{ item.location.city }}</td>
                <td class="align-middle">
                    {% if item.active is True %}
                        Active
                    {% else %}
                        Inactive
                    {% endif %}
                </td>
                <td>
                    <a class="btn btn-success" href="{% url 'companies:modify' item.id %}">Edit</a>
                    <a class="btn btn-danger" href="{% url 'companies:delete' item.id %}?page={{ page }}">Delete</a>
                    {% if item.active is True %}
                        <a class="btn btn-info" href="{% url 'companies:deactivate' item.id %}?page={{ page }}">Deactivate</a>
                    {% else %}
                        <a class="btn btn-success" href="{% url 'companies:activate' item.id %}?page={{ page }}">Activate</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex align-items-center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
                    {% else %}
                        <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
                {% else %}
                    <li class="disabled btn"><span>>></span></li>
                {% endif %}
                <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of {{ page_obj.paginator.count }}</span>
            </ul>
        {% endif %}
    </div>
{% endblock %}

web_app/templates/base.html
{% load static %}
<html lang="en">
<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'django.ico' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav class="mb-5">
                <a class="btn" href="/admin">Admin</a>
                {% if ready_to_work is False %}
                    <a href="{% url 'userprofile:stop_pontaj' %}" class="btn btn-danger">Oprire pontaj</a>
                {% else %}
                    <a href="{% url 'userprofile:start_pontaj' %}" class="btn btn-success">Pornire pontaj</a>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'locations:lista_locatii' %}">Locatii</a>
                    <a class="btn btn-primary" href="{% url 'companies:list_companies' %}">Companii</a>
                    <a class="btn" href="{% url 'logout' %}">Logout</a>
                {% endif %}

            </nav>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}
</body>
</html>